# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cproto3.proto\x12\x04main\"\xd4\x02\n\x0bTestMessage\x12\x0f\n\x07te_name\x18\x01 \x01(\t\x12\x0e\n\x06te_age\x18\x02 \x01(\x05\x12\x10\n\x08te_count\x18\x03 \x01(\x05\x12\x10\n\x08te_money\x18\x04 \x01(\x01\x12\x10\n\x08te_score\x18\x05 \x01(\x02\x12\x0e\n\x06te_fat\x18\x06 \x01(\x08\x12\x0f\n\x07te_char\x18\x07 \x01(\x0c\x12)\n\x06\x63hilds\x18\t \x01(\x0b\x32\x19.main.TestMessage.TeChild\x12,\n\x06te_map\x18\n \x03(\x0b\x32\x1c.main.TestMessage.TeMapEntry\x1a*\n\x07TeChild\x12\x0f\n\x07\x63h_name\x18\x01 \x01(\t\x12\x0e\n\x06\x63h_sex\x18\x02 \x01(\t\x1a,\n\nTeMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1a\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto3_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTMESSAGE_TEMAPENTRY._options = None
  _TESTMESSAGE_TEMAPENTRY._serialized_options = b'8\001'
  _TESTMESSAGE._serialized_start=23
  _TESTMESSAGE._serialized_end=363
  _TESTMESSAGE_TECHILD._serialized_start=247
  _TESTMESSAGE_TECHILD._serialized_end=289
  _TESTMESSAGE_TEMAPENTRY._serialized_start=291
  _TESTMESSAGE_TEMAPENTRY._serialized_end=335
  _TESTMESSAGE_STATUS._serialized_start=337
  _TESTMESSAGE_STATUS._serialized_end=363
# @@protoc_insertion_point(module_scope)
